eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://peer1:8763/eureka/,http://peer1:8764/eureka/
server:
  #当前服务端口号
  port: 8765
spring:
  application:
    #当前应用名称
    name: service-hi
